server:
  port: 9002
spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        server-addr: 192.168.192.192:1111 #配置nacos地址
management:
  endpoints:
    web:
      exposure:
        include: "*"